name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-clj:
    name: "Clojure (Java 16)"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Setup Java 16"
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 16
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: latest
    - name: Run tests
      run: bin/kaocha --reporter kaocha.report/documentation
